name: Build QMK firmware

on: 
  workflow_call: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: kimipsen/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: qmk/qmk_firmware
      qmk_ref: master

  publish:
    name: 'QMK Userspace Publish'
    uses: kimipsen/.github/.github/workflows/qmk_userspace_publish.yml@main
    if: always() && !cancelled()
    needs: build
    with:
      release_name: 1.0.0
